[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 2000
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
